[project]
name = "tcp-socket-chat"
version = "0.1.0"
description = "A lightweight, multi-threaded chat application built with TCP sockets that enables real-time group communication."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "emoji>=2.14.1",
]
